# Generated by Django 6.0.2 on 2026-02-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_is_verified_user_otp_alter_cart_user_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
